AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  anydl

  Sample SAM Template for anydl

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 80
    MemorySize: 1024
    Tracing: Active
    EphemeralStorage:
      Size: 4096
  Api:
    TracingEnabled: true
Resources:
  AnyDLFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Sid: DynamoDBCrudPolicy
              Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:DeleteItem
                - dynamodb:PutItem
                - dynamodb:Scan
                - dynamodb:Query
                - dynamodb:UpdateItem
                - dynamodb:BatchWriteItem
                - dynamodb:BatchGetItem
                - dynamodb:DescribeTable
              Resource: "arn:aws:dynamodb:eu-west-3:432189592299:table/anydl_users"
        - Version: "2012-10-17"
          Statement:
            - Sid: AWSSecretsManagerGetSecretValuePolicy
              Effect: Allow
              Action: secretsmanager:GetSecretValue
              Resource: "arn:aws:secretsmanager:eu-west-3:432189592299:secret:prod/anydl-GrwlDe"
      Architectures:
        - x86_64
      Events:
        AnyDL:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /webhook
            Method: post
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./anydl
      DockerTag: python3.9-v1
  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: "true"

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  AnyDLApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/webhook/"
  AnyDLFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt AnyDLFunction.Arn
  AnyDLFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt AnyDLFunctionRole.Arn
